name: saavn_play
description: Unofficial API client for JioSaavn. Search songs, albums, artists, playlists, podcasts, radio stations, and more.
version: 1.0.0

homepage: https://github.com/krishna-9099/saavn_play
repository: https://github.com/krishna-9099/saavn_play
issue_tracker: https://github.com/krishna-9099/saavn_play/issues
documentation: https://krishna-9099.github.io/saavn_play

topics:
  - saavn
  - jiosaavn
  - music
  - api-client
  - streaming

environment:
  sdk: '^3.0.0'

dependencies:
  dio: ^5.4.0
  json_annotation: ^4.9.0
  dart_des: ^1.0.2
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
